### ISSUE TITLE
wiki 문서 편집 권한 요청드립니다.

### ISSUE THREAD

**Issue by dakeshi** [golang-kr/doc#1]
안녕하세요. 한글 번역 참여하고 싶은데 wiki 접근 권한 허락해 주시면 감사하겠습니다.

**Comment by dh-yun** [comment]
편집권한 부여해드렸습니다.
그동안 업데이트를 많이 하질 못했는데 참여신청 환영합니다!
wiki 취지에 맞게 github 유저 누구나 수정가능하게 할지 고민도 해보겠습니다
