### ISSUE TITLE
Go learning path를 좀 더 명확하게 안내하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by dakeshi** [golang-kr/doc#2]
Effective Go를 읽다가 Go learning path 관련해서 좀 더 명확한 가이드라인이 필요할 것 같다는 생각이 드네요. Effective Go 에서는 선행학습 문서로 language specification, tour of Go, how to write Go code를 언급하고 있습니다. 때문에 학습순서로 보자면 1) how to write Go code, 2) tour of Go 3) language specification 4) Effective Go가 맞을 거 같아요. golang.org/doc에도 learning Go 섹션에 tour of Go가 가장 상위에 노출되어 있지만 학습 경로상으로는 how to write Go code가 우선인 것 같습니다. 따라서 Wiki 학습하기 페이지에서 1,2,3 같이 ordered list로 순서를 알려주면 새롭게 Go 언어를 학습하는 사람들에게 도움이 되지 않을까 싶네요.

**Comment by dh-yun** [comment]
Go 학습 순서는 주관적인 판단이 포함된 선택으로 생각합니다. 
위 예시는 Effective Go 저자의 의견으로써 의미는 있지만, 모든 상황에서 최선은 아닐 수도 있다고 생각해요. Go 를 처음 접하는 사람들 중에는 Go 컴파일 환경을 구성하기 전에, Go 언어 자체 샘플을 빨리 느껴보고 싶은 사람이 많을 수 있고, 그래서 golang.org/doc 에서도 tour of Go 를 가장 먼저 배치하고 있는 것으로 추측됩니다.

여튼 학습 순서에 있어서는 개인 별 선택 차이가 있을 수 있어 논외로 하고,
이곳 위키는 golang.org/doc 의 기본 구조와 순서는 맞추는 것이,  읽는 사람이나 번역에 기여하는 사람들에게 일관되어 혼동이 적을 것 같습니다.

**Comment by dakeshi** [comment]
> 이곳 위키는 golang.org/doc 의 기본 구조와 순서는 맞추는 것이, 읽는 사람이나 번역에 기여하는 사람들에게 일관되어 혼동이 적을 것 같습니다.

@dexyun 님 의견대로 golang.org와 일관성을 유지하는게 훨씬 나을것 같네요.
